ATT.PrintName = ARC9.UC.AttName("uc_muzzle_supp_giraffe")
ATT.MenuCategory = "ARC9 - Urban Coalition"

ATT.Icon = Material("entities/att/acwatt_uc_muzzle_supp_giraffe.png", "mips smooth")
ATT.Category = {"muzzle"}
ATT.SortOrder = 150
ATT.Model = "models/weapons/arccw/atts/uc_longass_silencer.mdl"
ATT.ModelOffset = Vector(2.1, 0, 0.00)
ATT.Scale = Vector(0.9, 1.25, 1.25)
ATT.ModelAngleOffset = Angle(0, 0, 0)
ATT.Silencer = true
ATT.MuzzleParticle = "muzzleflash_suppressed"
ATT.MuzzleDevice = true
ATT.ShootPitchMult = 1.1
ATT.ShootVolumeMult = 0.7
ATT.RangeMaxMult = 1.2
ATT.RangeMinMult = 1.2
ATT.BarrelLengthAdd = 10
ATT.AimDownSightsTimeMult = 1.15
ATT.SprintToFireTimeMult = 1.15
ATT.SpeedMultSights = 0.9
ATT.SwayMult = 1.15
ATT.InstallSound = "arccw_uc/common/gunsmith/suppressor_thread.ogg"
ATT.HookP_TranslateSound = ARC9.UC.SubsonicTail
