ATT.PrintName = ARC9.UC.AttName("ud_870_stock_sawnoff")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.ActivateElements = {"ud_870_stock_sawnoff"}

ATT.Icon = Material("entities/att/acwatt_ud_870_stock_sawnoff.png", "smooth mips")
ATT.Category = "ud_870_stock"
ATT.SpeedMult = 1.025
ATT.AimDownSightsTimeMult = 0.75
ATT.SprintToFireTimeMult = 0.75
ATT.SpeedMultSights = 1.1
ATT.SpeedMultShooting = 1.05
ATT.DeployTimeMult = 0.75
ATT.RecoilMult = 1.5
ATT.RecoilRandomSideMult = 2
ATT.VisualRecoilMult = 0.5
ATT.BarrelLengthAdd = -4
ATT.SwayMult = 3
ATT.ActivePos = Vector(0.078504, 2.500000, -1.497944)
ATT.HoldType = "shotgun"
ATT.HoldTypeSights = "ar2"
