ATT.PrintName = ARC9.UC.AttName("ud_glock_caliber_40sw")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.ActivateElements = {"cal_subsonic"}
ATT.ExcludeElements = {"powder_subsonic"}

ATT.SortOrder = 100
ATT.Icon = Material("entities/att/uc_bullets/40sw.png", "smooth mips")
ATT.Category = "ud_glock_caliber"
ATT.TriviaHook = ARC9.UC.TriviaHook("uc.trivia.calibre2", "uc.calibre.40_s_w")
ATT.DamageMaxMult = ARC9.UC.CalConv("9mm", "40sw", "max")
ATT.DamageMinMult = ARC9.UC.CalConv("9mm", "40sw", "min")
ATT.PenetrationMult = ARC9.UC.CalConv("9mm", "40sw", "pen")
ATT.RecoilMult = 1.15
ATT.PhysBulletMuzzleVelocity = 300 * ARC9.UC.Meter
ATT.ClipSizeMult = .9
ATT.ShellModel = "models/weapons/arccw/uc_shells/40sw.mdl"
ATT.ShellScale = 1
local path = ")weapons/arccw_ud/glock/"
local common = ")/arccw_uc/common/"
local tail = common .. "40sw/"
local fire40 = {path .. "fire-40-01.ogg",path .. "fire-40-02.ogg",path .. "fire-40-03.ogg",path .. "fire-40-04.ogg",path .. "fire-40-05.ogg",path .. "fire-40-06.ogg"}
local fire40sup = {path .. "fire-40-sup-01.ogg",path .. "fire-40-sup-02.ogg",path .. "fire-40-sup-03.ogg",path .. "fire-40-sup-04.ogg",path .. "fire-40-sup-05.ogg",path .. "fire-40-sup-06.ogg"}
local fire40dist = {tail .. "fire-dist-40sw-pistol-ext-01.ogg", tail .. "fire-dist-40sw-pistol-ext-02.ogg", tail .. "fire-dist-40sw-pistol-ext-03.ogg", tail .. "fire-dist-40sw-pistol-ext-04.ogg", tail .. "fire-dist-40sw-pistol-ext-05.ogg", tail .. "fire-dist-40sw-pistol-ext-06.ogg"}
local fire40distint = {common .. "fire-dist-int-pistol-heavy-01.ogg", common .. "fire-dist-int-pistol-heavy-02.ogg", common .. "fire-dist-int-pistol-heavy-03.ogg", common .. "fire-dist-int-pistol-heavy-04.ogg", common .. "fire-dist-int-pistol-heavy-05.ogg", common .. "fire-dist-int-pistol-heavy-06.ogg"}
ATT.ShootSoundSilenced = fire40sup
ATT.ShootSound = fire40
ATT.DistantShootSound = fire40dist
ATT.DistantShootSoundIndoor = fire40distint
