ATT.PrintName = ARC9.UC.AttName("ud_glock_caliber_380acp")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.ActivateElements = {"cal_subsonic"}
ATT.ExcludeElements = {"powder_subsonic"}

ATT.SortOrder = 50
ATT.Icon = Material("entities/att/uc_bullets/380acp.png", "smooth mips")
ATT.Category = "ud_glock_caliber"
ATT.TriviaHook = ARC9.UC.TriviaHook("uc.trivia.calibre2", "uc.calibre.380_acp")
ATT.DamageMaxMult = ARC9.UC.CalConv("9mm", "380acp", "max")
ATT.DamageMinMult = ARC9.UC.CalConv("9mm", "380acp", "min")
ATT.PenetrationMult = ARC9.UC.CalConv("9mm", "380acp", "pen")
ATT.RecoilMult = 0.65
ATT.PhysBulletMuzzleVelocity = 310 * ARC9.UC.Meter
ATT.ShellModel = "models/weapons/arccw/uc_shells/357sig.mdl"
ATT.ShellScale = 1
local common = ")/arccw_uc/common/"
local fire380 = "weapons/arccw_ud/glock/fire_380.ogg"
local fire380sup = { "weapons/arccw_ud/glock/fire_supp_380.ogg" }
local fire380dist = { "weapons/arccw_ud/glock/fire_dist_380.ogg" }
local fire380distint = {common .. "fire-dist-int-pistol-light-01.ogg",common .. "fire-dist-int-pistol-light-02.ogg",common .. "fire-dist-int-pistol-light-03.ogg",common .. "fire-dist-int-pistol-light-04.ogg",common .. "fire-dist-int-pistol-light-05.ogg",common .. "fire-dist-int-pistol-light-06.ogg"}
ATT.ShootSoundSilenced = fire380sup
ATT.ShootSound = fire380
ATT.DistantShootSound = fire380dist
ATT.DistantShootSoundIndoor = fire380distint
