ATT.PrintName = ARC9.UC.AttName("ud_glock_caliber_10auto")
ATT.MenuCategory = "ARC9 - Urban Coalition"

ATT.SortOrder = 80
ATT.Icon = Material("entities/att/uc_bullets/10.png", "smooth mips")
ATT.Category = "ud_glock_caliber"
ATT.TriviaHook = ARC9.UC.TriviaHook("uc.trivia.calibre2", "uc.calibre.10mm_auto")
ATT.DamageMaxMult = ARC9.UC.CalConv("9mm", "10mm", "max")
ATT.DamageMinMult = ARC9.UC.CalConv("9mm", "10mm", "min")
ATT.PenetrationMult = ARC9.UC.CalConv("9mm", "10mm", "pen")
ATT.RecoilMult = 1.25
ATT.RecoilRandomSideMult = 1.25
ATT.ReloadTimeMult = 1.15
ATT.MalfunctionMeanShotsToFailMult = 0.75
ATT.PhysBulletMuzzleVelocityMult = 400 / 375
ATT.ClipSizeMult = 0.9
ATT.ShellScale = 1
local path = ")weapons/arccw_ud/glock/"
local common = ")/arccw_uc/common/"
local tail = common .. "10x25/"
local fire10 = {path .. "fire-10-01.ogg",path .. "fire-10-02.ogg",path .. "fire-10-03.ogg",path .. "fire-10-04.ogg",path .. "fire-10-05.ogg",path .. "fire-10-06.ogg"}
local fire10sup = {path .. "fire-40-sup-01.ogg",path .. "fire-40-sup-02.ogg",path .. "fire-40-sup-03.ogg",path .. "fire-40-sup-04.ogg",path .. "fire-40-sup-05.ogg",path .. "fire-40-sup-06.ogg"}
local fire10dist = {tail .. "fire-dist-10x25-pistol-ext-01.ogg", tail .. "fire-dist-10x25-pistol-ext-02.ogg", tail .. "fire-dist-10x25-pistol-ext-03.ogg", tail .. "fire-dist-10x25-pistol-ext-04.ogg", tail .. "fire-dist-10x25-pistol-ext-05.ogg", tail .. "fire-dist-10x25-pistol-ext-06.ogg"}
local fire10distint = {common .. "fire-dist-int-pistol-heavy-01.ogg", common .. "fire-dist-int-pistol-heavy-02.ogg", common .. "fire-dist-int-pistol-heavy-03.ogg", common .. "fire-dist-int-pistol-heavy-04.ogg", common .. "fire-dist-int-pistol-heavy-05.ogg", common .. "fire-dist-int-pistol-heavy-06.ogg"}
ATT.ShootSoundSilenced = fire10sup
ATT.ShootSound = fire10
ATT.DistantShootSound = fire10dist
ATT.DistantShootSoundIndoor = fire10distint
