ATT.PrintName = ARC9.UC.AttName("ud_glock_caliber_45acp")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.ActivateElements = {"cal_subsonic"}
ATT.ExcludeElements = {"powder_subsonic"}

ATT.SortOrder = 70
ATT.Icon = Material("entities/att/uc_bullets/45acp.png", "smooth mips")
ATT.Category = "ud_glock_caliber"
ATT.TriviaHook = ARC9.UC.TriviaHook("uc.trivia.calibre2", "uc.calibre.45_acp")
ATT.DamageMaxMult = ARC9.UC.CalConv("9mm", "45acp", "max")
ATT.DamageMinMult = ARC9.UC.CalConv("9mm", "45acp", "min")
ATT.PenetrationMult = ARC9.UC.CalConv("9mm", "45acp", "pen")
ATT.RangeMinMult = 0.5
ATT.RecoilMult = 1.5
ATT.RecoilRandomSideMult = 1.5
ATT.MalfunctionMeanShotsToFailMult = 0.6
ATT.PhysBulletMuzzleVelocity = 320 * ARC9.UC.Meter
ATT.ClipSizeMult = 0.76
ATT.RPMMult = 0.7619
local path = ")weapons/arccw_ud/glock/"
local common = ")/arccw_uc/common/"
local tail = common .. "45acp/"
local fire45 = {path .. "fire-45-01.ogg",path .. "fire-45-02.ogg",path .. "fire-45-03.ogg",path .. "fire-45-04.ogg",path .. "fire-45-05.ogg",path .. "fire-45-06.ogg"}
local fire45sup =  {path .. "fire-45-sup-01.ogg",path .. "fire-45-sup-02.ogg",path .. "fire-45-sup-03.ogg",path .. "fire-45-sup-04.ogg",path .. "fire-45-sup-05.ogg",path .. "fire-45-sup-06.ogg"}
local fire45dist = {tail .. "fire-dist-45acp-pistol-ext-01.ogg",tail .. "fire-dist-45acp-pistol-ext-02.ogg",tail .. "fire-dist-45acp-pistol-ext-03.ogg",tail .. "fire-dist-45acp-pistol-ext-04.ogg",tail .. "fire-dist-45acp-pistol-ext-05.ogg",tail .. "fire-dist-45acp-pistol-ext-06.ogg"}
local fire45distint = {common .. "fire-dist-int-pistol-heavy-01.ogg", common .. "fire-dist-int-pistol-heavy-02.ogg", common .. "fire-dist-int-pistol-heavy-03.ogg", common .. "fire-dist-int-pistol-heavy-04.ogg", common .. "fire-dist-int-pistol-heavy-05.ogg", common .. "fire-dist-int-pistol-heavy-06.ogg"}
ATT.ShootSoundSilenced = fire45sup
ATT.ShootSound = fire45
ATT.DistantShootSound = fire45dist
ATT.DistantShootSoundIndoor = fire45distint
