ATT.PrintName = ARC9.UC.AttName("ud_glock_caliber_22lr")
ATT.MenuCategory = "ARC9 - Urban Coalition"

ATT.SortOrder = 00
ATT.Icon = Material("entities/att/uc_bullets/22lr.png", "smooth mips")
ATT.Category = "ud_glock_caliber"
ATT.TriviaHook = ARC9.UC.TriviaHook("uc.trivia.calibre2", "uc.calibre.22_long_rifle")
ATT.Ammo = "plinking"
ATT.DamageMaxMult = ARC9.UC.CalConv("9mm", "22lr", "max")
ATT.DamageMinMult = ARC9.UC.CalConv("9mm", "22lr", "min")
ATT.PenetrationMult = ARC9.UC.CalConv("9mm", "22lr", "pen") * 0.1
ATT.RecoilMult = 0.25
ATT.VisualRecoilMult = 0.25
ATT.RPMMult = 1.5
ATT.SpeedMultShooting = 1.2
ATT.TracerColor = Color(255, 255, 255, 200)
ATT.TracerSize = 0.5
ATT.PhysBulletMuzzleVelocityMult = 325 / 375
ATT.ClipSizeMult = 1.2
ATT.ShellModel = "models/weapons/arccw/uc_shells/22lr.mdl"
ATT.ShellScale = 1
ATT.ShellSounds = ARC9.TinyShellSoundsTable
local path = "arccw_uc/common/"
local fire22 = {path .. "fire-22-01.ogg",path .. "fire-22-02.ogg",path .. "fire-22-03.ogg",path .. "fire-22-04.ogg",path .. "fire-22-05.ogg",path .. "fire-22-06.ogg"}
local fire22sup = {path .. "fire-22-sup-01.ogg",path .. "fire-22-sup-02.ogg",path .. "fire-22-sup-03.ogg",path .. "fire-22-sup-04.ogg",path .. "fire-22-sup-05.ogg",path .. "fire-22-sup-06.ogg"}
local fire22dist = {path .. "fire-22-dist-01.ogg", path .. "fire-22-dist-02.ogg", path .. "fire-22-dist-03.ogg", path .. "fire-22-dist-04.ogg", path .. "fire-22-dist-05.ogg", path .. "fire-22-dist-06.ogg"}
local fire22distint = {path .. "fire-dist-int-pistol-light-01.ogg", path .. "fire-dist-int-pistol-light-02.ogg", path .. "fire-dist-int-pistol-light-03.ogg", path .. "fire-dist-int-pistol-light-04.ogg", path .. "fire-dist-int-pistol-light-05.ogg", path .. "fire-dist-int-pistol-light-06.ogg"}
ATT.ShootSoundSilenced = fire22sup
ATT.ShootSound = fire22
ATT.DistantShootSound = fire22dist
ATT.DistantShootSoundIndoor = fire22distint
