ATT.PrintName = ARC9.UC.AttName("ud_m16_barrel_10in")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.ActivateElements = {"barrel_11", "mount_11", "blen_11", "barrel_short", "patr1"}
ATT.ExcludeElements = {"hg_no11"}

ATT.Icon = Material("entities/att/acwatt_ud_m16_barrel_10_5.png", "smooth mips")
ATT.Category = "ud_m16_blen"
ATT.AimDownSightsTimeMult = 0.85
ATT.SprintToFireTimeMult = 0.85
ATT.SpeedMult = 1.025
ATT.SpeedMultSights = 1.1
ATT.UC_HipDispersionMult = 0.7
ATT.RPMMult = 1.15
ATT.RecoilMult = 1.5
ATT.SpreadMult = 2
ATT.RangeMaxMult = 0.5
ATT.SwayMult = 0.75
ATT.BarrelLengthAdd = -10
ATT.PhysBulletMuzzleVelocityMult = 0.729167
ATT.BoxModel = "models/items/boxsrounds.mdl"
