ATT.PrintName = ARC9.UC.AttName("ud_uzi_stock_folded")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.ActivateElements = {"ud_uzi_folded_stock"}

ATT.Icon = Material("entities/att/acwatt_ud_uzi_stock_folded.png", "smooth mips")
ATT.Category = "ud_uzi_stock"
ATT.InstallSound = "arccw_uc/common/stockslide.ogg"
ATT.Free = true
ATT.SortOrder = 2
ATT.RecoilMult = 1.15
ATT.RecoilRandomSideMult = 1.25
ATT.VisualRecoilMult = 2
ATT.SwayMult = 1.5
ATT.AimDownSightsTimeMult = 0.85
ATT.SprintToFireTimeMult = 0.85
ATT.SpeedMultSights = 1.05
ATT.SpeedMultShooting = 1.05
ATT.DeployTimeMult = 0.75
ATT.BarrelLengthAdd = -2
