ATT.PrintName = ARC9.UC.AttName("ur_1911_slide_m45")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_1911/slide_45tan.png","mips smooth")
ATT.Category = "ur_m1911_slide"
ATT.SortOrder = 5.1
ATT.RPMMult = 1.05
ATT.AimDownSightsTimeMult = 0.9
ATT.SprintToFireTimeMult = 0.9
ATT.SpreadMult = 0.8
ATT.RangeMinMult = 1.5
ATT.UC_HipDispersionMult = 1.25
