ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_329_barrel_m29.printname")
ATT.CompactName = ARC9:GetPhrase("ur_329_barrel_m29.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_329_barrel_m29.printname.variant1") end
ATT.Icon = Material("entities/att/acwatt_ur_329_barrel_m29.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_329_barrel_m29.description")
ATT.Category = "ur_329_barrel"
ATT.SortOrder = 6
ATT.SpreadMult = 0.7
ATT.RangeMaxMult = 1.5
ATT.RecoilMult = 0.85
ATT.AimDownSightsTimeMult = 1.25
ATT.SprintToFireTimeMult = 1.25
ATT.SwayMult = 1.15
ATT.UC_HipDispersionMult = 1.1
ATT.PhysBulletMuzzleVelocityMult = 1.15
ATT.BarrelLengthAdd = 4
ATT.RangeMinMult = 1.5
ATT.ActivateElements = {"ur_329_barrel_m29"}
ATT.DeployTimeMult = 1.15
