ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_329_barrel_pocket.printname")
ATT.CompactName = ARC9:GetPhrase("ur_329_barrel_pocket.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_329_barrel_pocket.printname.variant1") end
ATT.Icon = Material("entities/att/acwatt_ur_329_barrel_m29.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_329_barrel_pocket.description")
ATT.Category = "ur_329_barrel"
ATT.SortOrder = 3
ATT.SpreadMult = 1.3
ATT.RangeMaxMult = 0.75
ATT.RecoilMult = 1.3
ATT.AimDownSightsTimeMult = 0.85
ATT.SprintToFireTimeMult = 0.85
ATT.SwayMult = 0.85
ATT.UC_HipDispersionMult = 0.9
ATT.PhysBulletMuzzleVelocityMult = 0.85
ATT.BarrelLengthAdd = -1
ATT.Ignore = true
ATT.RangeMinMult = 0.75
ATT.ActivateElements = {"ur_329_barrel_pocket"}
ATT.DeployTimeMult = 0.75
