ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_329_barrel_master.printname")
ATT.CompactName = ARC9:GetPhrase("ur_329_barrel_master.compactname")
ATT.Icon = Material("entities/att/acwatt_ur_329_barrel_master.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_329_barrel_master.description")
ATT.Category = "ur_329_barrel"
ATT.SortOrder = 7
ATT.SpreadMult = 0.5
ATT.RangeMaxMult = 1.6
ATT.RecoilMult = 0.75
ATT.AimDownSightsTimeMult = 1.3
ATT.SprintToFireTimeMult = 1.3
ATT.SwayMult = 1.4
ATT.UC_HipDispersionMult = 1.15
ATT.PhysBulletMuzzleVelocityMult = 1.2
ATT.SpeedMultSights = .8
ATT.BarrelLengthAdd = 5
ATT.RangeMinMult = 1.6
ATT.ActivateElements = {"ur_329_barrel_master"}
ATT.DeployTimeMult = 1.25
