ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_aw_mag_10m.printname")
ATT.CompactName = ARC9:GetPhrase("ur_aw_mag_10m.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_aw_mag_10m.printname.variant1") end
ATT.SortOrder = 10
ATT.Icon = Material("entities/att/ur_aw/mag338_10.png", "mips smooth")
ATT.Description = ARC9:GetPhrase("ur_aw_mag_10m.description")
ATT.Category = "ur_aw_mag"
ATT.ClipSize = 10
ATT.AimDownSightsTimeMult = 1.25
ATT.SprintToFireTimeMult = 1.25
ATT.ReloadTimeMult = 6 / 5.55
ATT.SwayMult = 1.25
ATT.SpeedMult = 0.975
ATT.SpeedMultShooting = 0.95
ATT.UC_HipDispersionMult = 1.25
ATT.RequireElements = {"mag_300"}
ATT.ExcludeElements = {"mag_308"}
ATT.ActivateElements = {"ur_aw_mag_10m", "mag_ext_338"}
