ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_aw_stock_at.printname")
ATT.Description = ARC9:GetPhrase("ur_aw_stock_at.description")
ATT.Icon = Material("entities/att/ur_aw/stock_at.png", "mips smooth")
ATT.Category = {"ur_aw_stock"}
ATT.SortOrder = 3
ATT.AimDownSightsTimeMult = .85
ATT.SprintToFireTimeMult = .85
ATT.SwayMult = 1.25
ATT.RecoilMult = 1.1
ATT.ActivateElements = {"ur_aw_stock_at", "pistolgrip", "stock_at"}
