ATT.PrintName = ARC9.UC.AttName("ur_ak_hg_alpha")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_ak/handguards/alpha.png", "mips smooth")
ATT.Category = {"ur_ak_hg"}
ATT.SortOrder = 15.9
ATT.SwayMult = 1.15
ATT.SpeedMultSights = 1.15
ATT.RecoilMult = 1.08
ATT.ActivateElements = {"barrel_alpha", "ak_railedguard", "nodong"}
ATT.LHIK = true
ATT.ModelOffset = Vector(-22, -3.4, 3.3)
ATT.Model = "models/weapons/arccw/ak_lhik_u.mdl"
ATT.UC_ModelAngleOffset = Angle(5, 0, 0)
ATT.ModelAngleOffset = ARC9.UC.AttachmentAngle(ATT.UC_ModelAngleOffset)
