ATT.PrintName = ARC9.UC.AttName("ur_ak_stock_rpk")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_ak/stock/rpk.png", "mips smooth")
ATT.Category = {"ur_ak_stock"}
ATT.SortOrder = 3
ATT.RecoilMult = .85
ATT.SwayMult = .75
ATT.AimDownSightsTimeMult = 1.1
ATT.SprintToFireTimeMult = 1.1
ATT.SpeedMult = .9
ATT.ActivateElements = {"stock_rpk"}
