ATT.PrintName = ARC9.UC.AttName("ur_ak_barrel_rpk")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_ak/barrel/rpk.png", "mips smooth")
ATT.Category = {"ur_ak_barrel"}
ATT.SortOrder = 23
ATT.BarrelLengthAdd = 5
ATT.AimDownSightsTimeMult = 1.2
ATT.SprintToFireTimeMult = 1.2
ATT.SpeedMult = .95
ATT.SpeedMultSights = 0.8
ATT.SwayMult = 1.5
ATT.RecoilMult = .8
ATT.SpreadMult = .7
ATT.RangeMaxMult = 1.5
ATT.MalfunctionMeanShotsToFailMult = 2
ATT.UC_HipDispersionMult = 1.5
ATT.Bipod = true
ATT.RecoilMultBipod = .25
ATT.RecoilRandomSideMultBipod = .25
ATT.UC_BipodDispersionMult = .2
ATT.ActivateElements = {"barrel_rpk", "ak_barrelchange", "uc_noubgl"}
