ATT.PrintName = ARC9.UC.AttName("ur_ak_barrel_krinkov")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_ak/barrel/aksu.png", "mips smooth")
ATT.Category = {"ur_ak_barrel"}
ATT.SortOrder = 8
ATT.ShootPitchMult = 115 / 100
ATT.BarrelLengthAdd = -6
ATT.RPMMult = 1.131
ATT.AimDownSightsTimeMult = 0.8
ATT.SprintToFireTimeMult = 0.8
ATT.UC_HipDispersionMult = 0.8
ATT.SpeedMultSights = 1.1
ATT.SpeedMult = 1.02
ATT.SwayMult = 0.75
ATT.RecoilMult = 1.5
ATT.SpreadMult = 2
ATT.RangeMaxMult = .5
ATT.RangeMinMult = .5
ATT.ActivateElements = {"barrel_krinkov", "ak_barrelchange", "barrel_carbine", "ak_barrelkrinkov"}
ATT.LHIK = true
ATT.ModelOffset = Vector(-24, -3.1, 3.6)
ATT.Model = "models/weapons/arccw/ak_lhik_u.mdl"
ATT.UC_ModelAngleOffset = Angle(10, 0, 0)
ATT.ModelAngleOffset = ARC9.UC.AttachmentAngle(ATT.UC_ModelAngleOffset)
