ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_aw_barrel_short.printname")
ATT.CompactName = ARC9:GetPhrase("ur_aw_barrel_short.compactname")
ATT.Icon = Material("entities/att/ur_aw/bar_short.png", "mips smooth")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_aw_barrel_short.printname.variant1") end
ATT.SortOrder = 20
ATT.Description = ARC9:GetPhrase("ur_aw_barrel_short.description")
ATT.Category = "ur_aw_barrel"
ATT.AimDownSightsTimeMult = 0.75
ATT.SprintToFireTimeMult = 0.75
ATT.SwayMult = 0.5
ATT.UC_HipDispersionMult = 0.5
ATT.SpeedMult = 1.05
ATT.BarrelLengthAdd = -4
ATT.RangeMaxMult = 0.3
ATT.SpreadMult = 4
ATT.RecoilMult = 1.25
ATT.RangeMinMult = 0.3
ATT.ActivateElements = {"ur_aw_barrel_short", "barrel_short"}
