ATT.PrintName = ARC9.UC.AttName("ur_ak_stock_skeletal")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_ak/stock/saiga.png", "mips smooth")
ATT.Category = {"ur_ak_stock"}
ATT.SortOrder = 2
ATT.AimDownSightsTimeMult = .8
ATT.SprintToFireTimeMult = .8
ATT.SpeedMultSights = 1.1
ATT.SpeedMult = 1.05
ATT.SwayMult = 1.1
ATT.RecoilMult = 1.35
ATT.RecoilRandomSideMult = 1.15
ATT.ActivateElements = {"stock_skeletal"}
ATT.Ignore = true
