ATT.PrintName = ARC9.UC.AttName("ur_ak_stock_alpha")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_ak/stock/helix.png", "mips smooth")
ATT.Category = {"ur_ak_stock"}
ATT.SortOrder = 2
ATT.SpeedMultShooting = 1.1
ATT.SpeedMultSights = 1.15
ATT.RecoilRandomSideMult = 1.5
ATT.SwayMult = 1.25
ATT.BarrelLengthAdd = -2
ATT.ActivateElements = {"stock_alpha"}
