ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_aw_stock_ru.printname")
ATT.CompactName = ARC9:GetPhrase("ur_aw_stock_ru.compactname")
ATT.Icon = Material("entities/att/ur_aw/stock_ru.png", "mips smooth")
if ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_aw_stock_ru.printname.variant1") end
ATT.Description = ARC9:GetPhrase("ur_aw_stock_ru.description")
ATT.Category = {"ur_aw_stock"}
ATT.SortOrder = 2.1
ATT.SpeedMult = 1.08
ATT.UC_MoveDispersionMult = .6
ATT.AimDownSightsTimeMult = .9
ATT.SprintToFireTimeMult = .9
ATT.SwayMult = 1.5
ATT.RecoilRandomSideMult = 1.5
ATT.ActivateElements = {"ur_aw_stock_ru", "pistolgrip", "stock_ru"}
