ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_aw_mag_10.printname")
ATT.CompactName = ARC9:GetPhrase("ur_aw_mag_10.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_aw_mag_10.printname.variant1") end
ATT.SortOrder = 10
ATT.Icon = Material("entities/att/ur_aw/mag308_10.png", "mips smooth")
ATT.Description = ARC9:GetPhrase("ur_aw_mag_10.description")
ATT.Category = "ur_aw_mag"
ATT.ClipSize = 10
ATT.AimDownSightsTimeMult = 1.25
ATT.SprintToFireTimeMult = 1.25
ATT.ReloadTimeMult = 5.675 / 5.15
ATT.SwayMult = 1.25
ATT.SpeedMult = 0.975
ATT.SpeedMultShooting = 0.95
ATT.UC_HipDispersionMult = 1.25
ATT.ExcludeElements = {"mag_338", "mag_300"}
ATT.ActivateElements = {"ur_aw_mag_10", "mag_ext"}
