ATT.PrintName = ARC9.UC.AttName("ur_ak_barrel_vityaz")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_ak/barrel/smg.png", "mips smooth")
ATT.Category = {"ur_ak_barrel"}
ATT.SortOrder = 9
ATT.BarrelLengthAdd = -5
ATT.ShootPitchMult = 115 / 100
ATT.RPMMult = 1.131
ATT.AimDownSightsTimeMult = 0.7
ATT.SprintToFireTimeMult = 0.7
ATT.UC_HipDispersionMult = 0.7
ATT.SpeedMultSights = 1.12
ATT.SpeedMult = 1.03
ATT.SwayMult = 0.85
ATT.RecoilMult = 1.4
ATT.SpreadMult = 1.5
ATT.RangeMaxMult = 0.65
ATT.RangeMinMult = 0.65
ATT.ActivateElements = {"barrel_vityaz", "ak_barrelchange", "barrel_carbine", "ak_railedguard"}
ATT.LHIK = true
ATT.LHIK_Priority = -2
ATT.ModelOffset = Vector(-24, -3.4, 3.3)
ATT.Model = "models/weapons/arccw/ak_lhik_u.mdl"
ATT.UC_ModelAngleOffset = Angle(10, 0, 0)
ATT.ModelAngleOffset = ARC9.UC.AttachmentAngle(ATT.UC_ModelAngleOffset)
