ATT.PrintName = ARC9.UC.AttName("ur_ak_barrel_vepr")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_ak/barrel/vepr.png", "mips smooth")
ATT.Category = {"ur_ak_barrel"}
ATT.SortOrder = 20
ATT.BarrelLengthAdd = 4
ATT.AimDownSightsTimeMult = 1.15
ATT.SprintToFireTimeMult = 1.15
ATT.SpeedMult = .97
ATT.SpeedMultSights = 0.85
ATT.RecoilMult = 0.85
ATT.SpreadMult = 0.5
ATT.RangeMaxMult = 1.5
ATT.UC_HipDispersionMult = 1.25
ATT.ShootPitchMult = 0.9
ATT.RPMMult = 0.8
ATT.ActivateElements = {"barrel_vepr", "ak_barrelchange"}
