ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_aw_stock_ru_rubber.printname")
ATT.CompactName = ARC9:GetPhrase("ur_aw_stock_ru_rubber.compactname")
ATT.Icon = Material("entities/att/ur_aw/stock_rurubber.png", "mips smooth")
if ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_aw_stock_ru_rubber.printname.variant1") end
ATT.Description = ARC9:GetPhrase("ur_aw_stock_ru_rubber.description")
ATT.Category = {"ur_aw_stock"}
ATT.SortOrder = 2
ATT.UC_MoveDispersionMult = .6
ATT.SwayMult = 1.25
ATT.RecoilRandomSideMult = 1.2
ATT.ActivateElements = {"ur_aw_stock_ru_rubber", "pistolgrip", "stock_ru_rubber"}
