ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_aw_stock_none.printname")
ATT.Description = ARC9:GetPhrase("ur_aw_stock_none.description")
ATT.Icon = Material("entities/att/ur_aw/stock_removed.png", "mips smooth")
ATT.Category = {"ur_aw_stock"}
ATT.Free = true
ATT.SortOrder = -1
ATT.AimDownSightsTimeMult = 0.75
ATT.SprintToFireTimeMult = 0.75
ATT.RecoilMult = 2.5
ATT.RecoilRandomSideMult = 1.55
ATT.SpeedMultSights = 1.25
ATT.SpeedMult = 1.1
ATT.SpeedMultShooting = 1.15
ATT.BarrelLengthAdd = -9
ATT.SwayMult = 3.5
ATT.ActivateElements = {"ur_aw_stock_none", "pistolgrip", "stock_none"}
ATT.DeployTimeMult = 0.6
