ATT.PrintName = ARC9.UC.AttName("ur_ak_muzzle_ak74")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_ak/muzzle_74m.png", "mips smooth")
ATT.Category = {"ur_ak_muzzle"}
ATT.RecoilMult = .95
ATT.RecoilRandomSideMult = .65
ATT.BarrelLengthAdd = 2.5
ATT.AimDownSightsTimeMult = 1.05
ATT.SprintToFireTimeMult = 1.05
ATT.SwayMult = 1.25
ATT.SortOrder = 999
ATT.InstallSound = "arccw_uc/common/gunsmith/suppressor_thread.ogg"
ATT.ActivateElements = {"muzzle_ak74"}
ATT.ExcludeElements = {"ak_barrelchange", "cal_545", "cal_556"}
