ATT.PrintName = ARC9.UC.AttName("ur_ak_muzzle_akm")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_ak/muzzle_m.png", "mips smooth")
ATT.Category = {"ur_ak_muzzle"}
ATT.RecoilMult = .9
ATT.RecoilRandomSideMult = .95
ATT.BarrelLengthAdd = 1
ATT.AimDownSightsTimeMult = 1.025
ATT.SprintToFireTimeMult = 1.025
ATT.SwayMult = 1.05
ATT.ShootVolumeMult = 1.1
ATT.SortOrder = 998
ATT.InstallSound = "arccw_uc/common/gunsmith/suppressor_thread.ogg"
ATT.ActivateElements = {"muzzle_akm"}
ATT.ExcludeElements = {"ak_barrelchange"}
ATT.RequireElements = {{"cal_default"}}
ATT.Ignore = true
