ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_deagle_barrel_compact.printname")
ATT.CompactName = ARC9:GetPhrase("ur_deagle_barrel_compact.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_deagle_barrel_compact.printname.variant1") end
ATT.Icon = Material("entities/att/acwatt_ur_deagle_barrel_compact.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_deagle_barrel_compact.description")
ATT.Category = "ur_deagle_barrel"
ATT.SortOrder = 5.5
ATT.SpreadMult = 1.25
ATT.RangeMaxMult = 0.9
ATT.AimDownSightsTimeMult = 0.9
ATT.SprintToFireTimeMult = 0.9
ATT.SwayMult = 0.8
ATT.BarrelLengthAdd = -2
ATT.UC_HipDispersionMult = 0.95
ATT.RangeMinMult = 0.9
ATT.ActivateElements = {"ur_deagle_barrel_compact"}
ATT.DeployTimeMult = 0.9
