ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_dbs_barrel_compact.printname")
ATT.CompactName = ARC9:GetPhrase("ur_dbs_barrel_compact.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_dbs_barrel_compact.printname.variant1") end
ATT.Icon = Material("entities/att/ur_dbs/bcomp.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_dbs_barrel_compact.description")
ATT.Category = {"ur_db_barrel"}
ATT.SwayMult = .75
ATT.BarrelLengthAdd = -9
ATT.AimDownSightsTimeMult = .9
ATT.SprintToFireTimeMult = .9
ATT.UC_HipDispersionMult = 0.8
ATT.RecoilMult = 1.2
ATT.SpreadMult = 1.25
ATT.RangeMaxMult = .85
ATT.SortOrder = 18
ATT.RangeMinMult = .85
ATT.ActivateElements = {"ur_dbs_barrel_compact", "barrel_compact"}
