ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_dbs_barrel_sawedoffplus.printname")
ATT.CompactName = ARC9:GetPhrase("ur_dbs_barrel_sawedoffplus.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_dbs_barrel_sawedoffplus.printname.variant1") end
ATT.Icon = Material("entities/att/ur_dbs/bswp.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_dbs_barrel_sawedoffplus.description")
ATT.Category = {"ur_db_barrel"}
ATT.ModelOffset = Vector(-21, -2.2, 8.3)
ATT.Model = "models/weapons/arccw/ur_g3_lhik_slim.mdl"
ATT.NoDraw = true
ATT.LHIK = true
ATT.LHIKPriority = 0
ATT.SortOrder = 10
ATT.BarrelLengthAdd = -20
ATT.SwayMult = .5
ATT.AimDownSightsTimeMult = .75
ATT.SprintToFireTimeMult = .75
ATT.SpeedMult = 1.05
ATT.UC_HipDispersionMult = 0.5
ATT.RecoilMult = 1.5
ATT.SpreadMult = 2.5
ATT.RangeMaxMult = .5
ATT.RangeMinMult = .5
ATT.ActivateElements = {"ur_dbs_barrel_sawedoffplus", "sawnoff", "barrel_swplus"}
ATT.DeployTimeMult = .75
