ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_deagle_barrel_compen.printname")
ATT.CompactName = ARC9:GetPhrase("ur_deagle_barrel_compen.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_deagle_barrel_compen.printname.variant1") end
ATT.Icon = Material("entities/att/acwatt_ur_deagle_barrel_compensated.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_deagle_barrel_compen.description")
ATT.Category = "ur_deagle_barrel"
ATT.SortOrder = 6
ATT.RecoilMult = 0.85
ATT.RecoilRandomSideMult = 0.75
ATT.ShootVolumeMult = 1.1
ATT.RangeMaxMult = 0.95
ATT.ShootPitchMult = 0.95
ATT.RPMMult = .9
ATT.RangeMinMult = 0.95
ATT.ActivateElements = {"ur_deagle_barrel_compen", "barrel_annihilator"}
