ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_dbs_barrel_sawedoff.printname")
ATT.CompactName = ARC9:GetPhrase("ur_dbs_barrel_sawedoff.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_dbs_barrel_sawedoff.printname.variant1") end
ATT.Icon = Material("entities/att/ur_dbs/bsw.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_dbs_barrel_sawedoff.description")
ATT.Category = {"ur_db_barrel"}
ATT.SortOrder = 12
ATT.BarrelLengthAdd = -16
ATT.SwayMult = .6
ATT.AimDownSightsTimeMult = .85
ATT.SprintToFireTimeMult = .85
ATT.SpeedMult = 1.03
ATT.UC_HipDispersionMult = 0.75
ATT.RecoilMult = 1.4
ATT.SpreadMult = 2
ATT.RangeMaxMult = .65
ATT.RangeMinMult = .65
ATT.ActivateElements = {"ur_dbs_barrel_sawedoff", "sawnoff", "barrel_sw"}
ATT.DeployTimeMult = .85
