ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_dbs_stock_sawedoff.printname")
ATT.CompactName = ARC9:GetPhrase("ur_dbs_stock_sawedoff.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_dbs_stock_sawedoff.printname.variant1") end
ATT.Icon = Material("entities/att/ur_dbs/ssw.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_dbs_stock_sawedoff.description")
ATT.Category = {"ur_db_stock"}
ATT.Free = true
ATT.SortOrder = -1
ATT.SpeedMult = 1.05
ATT.AimDownSightsTimeMult = 0.75
ATT.SprintToFireTimeMult = 0.75
ATT.RecoilMult = 1.4
ATT.RecoilRandomSideMult = 1.25
ATT.SpeedMultSights = 1.2
ATT.SpeedMultShooting = 1.15
ATT.BarrelLengthAdd = -12
ATT.SwayMult = 3
ATT.ActivateElements = {"ur_dbs_stock_sawedoff", "stock_sw"}
ATT.DeployTimeMult = 0.75
