ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_deagle_grip_rubber.printname")
ATT.CompactName = ARC9:GetPhrase("ur_deagle_grip_rubber.compactname")
ATT.Icon = Material("entities/att/acwatt_ur_deagle_grip_rubber.png", "mips smooth")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_deagle_grip_rubber.printname.variant1") end
ATT.Description = ARC9:GetPhrase("ur_deagle_grip_rubber.description")
ATT.Category = "ur_deagle_grip"
ATT.RecoilMult = 0.95
ATT.RecoilRandomSideMult = 0.9
ATT.SpeedMultSights = 0.95
ATT.ActivateElements = {"ur_deagle_grip_rubber"}
