ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_dbs_barrel_mid.printname")
ATT.CompactName = ARC9:GetPhrase("ur_dbs_barrel_mid.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_dbs_barrel_mid.printname.variant1") end
ATT.Icon = Material("entities/att/ur_dbs/bmid.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_dbs_barrel_mid.description")
ATT.Category = {"ur_db_barrel"}
ATT.SortOrder = 22
ATT.SwayMult = .85
ATT.BarrelLengthAdd = -4
ATT.AimDownSightsTimeMult = 0.95
ATT.SprintToFireTimeMult = 0.95
ATT.UC_HipDispersionMult = 0.9
ATT.RecoilMult = 1.1
ATT.SpreadMult = 1.1
ATT.RangeMaxMult = 0.9
ATT.RangeMinMult = 0.9
ATT.ActivateElements = {"ur_dbs_barrel_mid", "barrel_mid"}
