ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_deagle_barrel_marksman.printname")
ATT.CompactName = ARC9:GetPhrase("ur_deagle_barrel_marksman.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_deagle_barrel_marksman.printname.variant1") end
ATT.Icon = Material("entities/att/acwatt_ur_deagle_barrel_police.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_deagle_barrel_marksman.description")
ATT.Category = "ur_deagle_barrel"
ATT.SortOrder = 10
ATT.SpreadMult = 0.5
ATT.RangeMaxMult = 2
ATT.RecoilMult = 0.75
ATT.AimDownSightsTimeMult = 1.25
ATT.SprintToFireTimeMult = 1.25
ATT.SwayMult = 1.25
ATT.ShootPitchMult = 0.9
ATT.UC_HipDispersionMult = 1.2
ATT.BarrelLengthAdd = 10
ATT.RangeMinMult = 2
ATT.ActivateElements = {"ur_deagle_barrel_marksman"}
ATT.DeployTimeMult = 1.5
