ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_deagle_grip_wood.printname")
ATT.CompactName = ARC9:GetPhrase("ur_deagle_grip_wood.compactname")
ATT.Icon = Material("entities/att/acwatt_ur_deagle_grip_plastic.png", "smooth mips")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_deagle_grip_wood.printname.variant1") end
ATT.Description = ARC9:GetPhrase("ur_deagle_grip_wood.description")
ATT.Category = "ur_deagle_grip"
ATT.RecoilMult = 1.05
ATT.RecoilRandomSideMult = 1.1
ATT.AimDownSightsTimeMult = 0.95
ATT.SprintToFireTimeMult = 0.95
ATT.ActivateElements = {"ur_deagle_grip_wood", "ur_deagle_grip_wooden"}
