ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_deagle_barrel_ext.printname")
ATT.CompactName = ARC9:GetPhrase("ur_deagle_barrel_ext.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_deagle_barrel_ext.printname.variant1") end
ATT.Icon = Material("entities/att/acwatt_ur_deagle_barrel_long.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_deagle_barrel_ext.description")
ATT.Category = "ur_deagle_barrel"
ATT.SortOrder = 7
ATT.SpreadMult = 0.8
ATT.RangeMaxMult = 1.25
ATT.RecoilMult = 0.9
ATT.AimDownSightsTimeMult = 1.1
ATT.SprintToFireTimeMult = 1.1
ATT.SwayMult = 1.15
ATT.UC_HipDispersionMult = 1.1
ATT.BarrelLengthAdd = 4
ATT.RangeMinMult = 1.25
ATT.ActivateElements = {"ur_deagle_barrel_ext"}
ATT.DeployTimeMult = 1.25
