ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_g3_mag_40_556.printname")
ATT.CompactName = ARC9:GetPhrase("ur_g3_mag_40_556.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_g3_mag_40_556.printname.variant1") end
ATT.Icon = Material("entities/att/ur_g3/mag556_40.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_g3_mag_40_556.description")
ATT.Category = {"ur_g3_mag"}
ATT.SortOrder = 10
ATT.ClipSize = 40
ATT.ClipSize_Priority = 2
ATT.AimDownSightsTimeMult = 1.1
ATT.SprintToFireTimeMult = 1.1
ATT.ReloadTimeMult = 1.15
ATT.SwayMult = 1.5
ATT.SpeedMult = 0.975
ATT.SpeedMultShooting = 0.95
ATT.RequireElements = {"cal_556"}
ATT.ActivateElements = {"ur_g3_mag_40_556"}
