ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_g3_barrel_15.printname")
ATT.CompactName = ARC9:GetPhrase("ur_g3_barrel_15.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_g3_barrel_15.printname.variant1") end
ATT.Icon = Material("entities/att/ur_g3/barrel_33.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_g3_barrel_15.description")
ATT.Category = "ur_g3_barrel"
ATT.SortOrder = 15
ATT.AimDownSightsTimeMult = 0.9
ATT.SprintToFireTimeMult = 0.9
ATT.BarrelLengthAdd = -4
ATT.SpeedMultSights = 1.05
ATT.SwayMult = 0.85
ATT.RecoilMult = 1.1
ATT.SpreadMult = 1.1
ATT.RangeMaxMult = 0.75
ATT.RangeMinMult = 0.75
ATT.ActivateElements = {"ur_g3_barrel_15", "g3_not8"}
