ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_g3_bayobipod_bipod.printname")
ATT.CompactName = ARC9:GetPhrase("ur_g3_bayobipod_bipod.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_g3_bayobipod_bipod.printname.variant1") end
ATT.Icon = false
ATT.Description = ARC9:GetPhrase("ur_g3_bayobipod_bipod.description")
ATT.Category = "ur_g3_bayobipod"
ATT.SortOrder = 998
ATT.Free = true
ATT.Ignore = true
ATT.ActivateElements = {"ur_g3_bayobipod_bipod"}
