ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_g3_barrel_12.printname")
ATT.CompactName = ARC9:GetPhrase("ur_g3_barrel_12.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_g3_barrel_12.printname.variant1") end
ATT.Icon = Material("entities/att/ur_g3/barrel_k.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_g3_barrel_12.description")
ATT.Category = "ur_g3_barrel"
ATT.SortOrder = 12
ATT.AimDownSightsTimeMult = 0.9
ATT.SprintToFireTimeMult = 0.9
ATT.BarrelLengthAdd = -4
ATT.SpeedMultSights = 1.05
ATT.UC_HipDispersionMult = 0.9
ATT.SwayMult = 0.7
ATT.RecoilMult = 1.15
ATT.SpreadMult = 1.5
ATT.RangeMaxMult = 0.5
ATT.RPMMult = 1.1
ATT.RangeMinMult = 0.5
ATT.ActivateElements = {"ur_g3_barrel_12", "g3_not8"}
