ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_g3_stock_psg.printname")
ATT.CompactName = ARC9:GetPhrase("ur_g3_stock_psg.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_g3_stock_psg.printname.variant1") end
ATT.Icon = Material("entities/att/ur_g3/stock_psg.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_g3_stock_psg.description")
ATT.Category = {"ur_g3_stock"}
ATT.SortOrder = 11
ATT.RecoilMult = 0.85
ATT.SwayMult = .6
ATT.AimDownSightsTimeMult = 1.1
ATT.SprintToFireTimeMult = 1.1
ATT.SpeedMult = 0.8
ATT.ActivateElements = {"ur_g3_stock_psg"}
