ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_g3_mag_10.printname")
ATT.CompactName = ARC9:GetPhrase("ur_g3_mag_10.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_g3_mag_10.printname.variant1") end
ATT.Icon = Material("entities/att/ur_g3/mag10.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_g3_mag_10.description")
ATT.Category = {"ur_g3_mag"}
ATT.SortOrder = 14
ATT.ClipSize = 10
ATT.AimDownSightsTimeMult = 0.9
ATT.SprintToFireTimeMult = 0.9
ATT.ReloadTimeMult = 0.95
ATT.SwayMult = 0.7
ATT.SpeedMult = 1.025
ATT.SpeedMultShooting = 1.05
ATT.UC_HipDispersionMult = 0.85
ATT.ExcludeElements = {"cal_556"}
ATT.ActivateElements = {"ur_g3_mag_10"}
