ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_g3_mag_20_556.printname")
ATT.CompactName = ARC9:GetPhrase("ur_g3_mag_20_556.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_g3_mag_20_556.printname.variant1") end
ATT.Icon = Material("entities/att/ur_g3/mag556_20.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_g3_mag_20_556.description")
ATT.Category = {"ur_g3_mag"}
ATT.SortOrder = 10
ATT.ClipSize = 20
ATT.ClipSize_Priority = 2
ATT.AimDownSightsTimeMult = 0.85
ATT.SprintToFireTimeMult = 0.85
ATT.ReloadTimeMult = 0.9
ATT.SwayMult = 0.75
ATT.SpeedMult = 1.025
ATT.SpeedMultSights = 1.05
ATT.SpeedMultShooting = 1.05
ATT.RequireElements = {"cal_556"}
ATT.ActivateElements = {"ur_g3_mag_20_556"}
