ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.PrintName = ARC9:GetPhrase("ur_g3_stock_sg.printname")
ATT.CompactName = ARC9:GetPhrase("ur_g3_stock_sg.compactname")
if not ARC9:UseTrueNames() then ATT.PrintName = ARC9:GetPhrase("ur_g3_stock_sg.printname.variant1") end
ATT.Icon = Material("entities/att/ur_g3/stock_sg.png", "smooth mips")
ATT.Description = ARC9:GetPhrase("ur_g3_stock_sg.description")
ATT.Category = {"ur_g3_stock"}
ATT.SortOrder = 11
ATT.SwayMult = .75
ATT.AimDownSightsTimeMult = 1.075
ATT.SprintToFireTimeMult = 1.075
ATT.ActivateElements = {"ur_g3_stock_sg"}
