ATT.PrintName = ARC9.UC.AttName("ur_spas12_stock_none")
ATT.MenuCategory = "ARC9 - Urban Coalition"
ATT.Icon = Material("entities/att/ur_spas/grip_std.png", "smooth mips")
ATT.Category = "ur_spas12_stock"
ATT.Free = true
ATT.SortOrder = -1
ATT.SpeedMult = 1.05
ATT.AimDownSightsTimeMult = 0.5
ATT.SprintToFireTimeMult = 0.5
ATT.DeployTimeMult = 0.75
ATT.RecoilMult = 1.4
ATT.RecoilRandomSideMult = 2
ATT.SpeedMultSights = 1.2
ATT.SpeedMultShooting = 1.15
ATT.BarrelLengthAdd = -12
ATT.SwayMult = 3
